name: Lint

on:
  push:
    branches: [master,dev]
  pull_request:
    branches: [master,dev]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        run: yarn install

      - name: Run linters
        run: yarn fix

      - name: Add changes to Git tracking
        id: git_commit
        run: |
          git config --global user.email "it@dipperin.io"
          git config --global user.name "Github Action"
          changes=$(git status -s | wc -l)
          echo ::set-output name=changes::$changes
          echo $changes
          if [ "$changes" -gt "0" ] ; then
            echo "commit"
            git add -A .
            git commit -am 'lint'
          fi

      - name: push
        if: steps.git_commit.outputs.changes > 0
        uses: github-actions-x/commit@v2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'lint'
          force-add: 'false'
          name: Github Action
          email: it@dipperin.io
